SELECT 'DROP DATABASE';
DROP DATABASE IF EXISTS cl113afrv;

SELECT 'CREATE DATABASE';
CREATE DATABASE cl113afrv;

SELECT 'USE DATABASE';
USE cl113afrv;

SELECT 'CREATE races';
CREATE TABLE races (
	id INT NOT NULL AUTO_INCREMENT,
	name TEXT,
	PRIMARY KEY(id)
)ENGINE=InnoDB;

SELECT 'CREATE players';
CREATE TABLE players (
	id INT NOT NULL AUTO_INCREMENT,
	name TEXT,
	race_id INT,
	score INT,
	PRIMARY KEY(id),
	FOREIGN KEY(race_id) REFERENCES races(id) ON DELETE CASCADE
)ENGINE=InnoDB;